services:
  postgres:
    image: postgres:17
    container_name: tripwise-postgres
    restart: unless-stopped
    environment:
      PGDATABASE: railway
      PGUSER: postgres
      POSTGRES_PASSWORD: oaQRaGOTSKBgRBpFFJEIXFxPOEsyMVQI
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


