# Generated by Django 6.1 on 2026-09-08 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_itineraryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('ACCOMMODATION', 'Accommodation'), ('TRANSPORTATION', 'Transportation'), ('FOOD', 'Food'), ('ACTIVITIES', 'Activities'), ('SHOPPING', 'Shopping'), ('OTHER', 'Other')], max_length=20)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='trips.trip')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trip', 'category'), name='unique_budget_category_per_trip'), models.CheckConstraint(condition=models.Q(('estimated_amount__gte', 0)), name='estimated_amount_non_negative'), models.CheckConstraint(condition=models.Q(('actual_amount__gte', 0)), name='actual_amount_non_negative')],
            },
        ),
    ]
