# Generated by Django 6.1 on 2026-09-04 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('destination_type', models.CharField(choices=[('CITY', 'City'), ('ATTRACTION', 'Attraction'), ('NATIONAL_PARK', 'National Park'), ('BEACH', 'Beach'), ('LANDMARK', 'Landmark'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country'], name='destination_country_2ade19_idx'), models.Index(fields=['city'], name='destination_city_ec88bc_idx'), models.Index(fields=['destination_type'], name='destination_destina_bdaff1_idx')],
            },
        ),
    ]
